public class setPreviousClass {
    // public static void afterInsert(List<Project__c> newList){
        
    //     List<Yearly_Growth__C> yrgList=new List<Yearly_Growth__C>();
        
    //     for(Project__c prj : newList){
    //         System.debug(prj.Id);
    //         ID prjId=prj.Id;
            
    //         List<Yearly_Growth__C> query = [Select ID,Year_Number__c from Yearly_Growth__C Where Project__r.Id = :prjId];
            
    //         System.debug(query);
            
    //     }
        
    // }
}